commands:
  - name: python3
    args: ["/home/sn0wb/action/XSStrike/xsstrike.py", "-u"]

  - name: whois

  - name: nslookup

  - name: python3
    args: ["/home/sn0wb/action/FinalRecon/finalrecon.py","--headers", "--whois", "--url"]

  - name: nikto
    args: ["-h"]



