commands:
  - name: whois
    command: "whois {target}"
  
  - name: nslookup
    command: "nslookup {target}"

  - name: gobuster_dns
    command: "gobuster dns -w /usr/share/wordlists/seclist/Discovery/DNS/subdomains-top1million-20000.txt -t 50 -d {target}"

  - name: gobuster_dir
    command: "gobuster dir -w /usr/share/wordlists/seclist/Discovery/Web-Content/directory-list-2.3-small.txt -t 50 -u {target}"

  - name: nikto
    command: "nikto -h {target}"

  - name: finalrecon
    command: "python3 /home/sn0wb/action/FinalRecon/finalrecon.py -nb --crawl --headers --whois --dns --dir --full -ps --url http://{target}"    

