recon:
  - name: whois
    command: "whois {target}"
  
  - name: nslookup
    command: "nslookup {target}"

  - name: whatweb
    command: "whatweb {target}"
    
  - name: gobuster_dns
    command: "gobuster dns -w /usr/share/wordlists/seclist/Discovery/DNS/subdomains-top1million-20000.txt -t 50 -d {target} | grep -vE 'Progress'"

  - name: fuf_did
    command: "ffuf -w /usr/share/wordlists/seclist/Discovery/Web-Content/directory-list-2.3-small.txt:FUZZ -u http://{target}/FUZZ -recursion -recursion-depth 1 -t 50 -fc 301"

  - name: nikto
    command: "nikto -h {target}"

  - name: finalrecon
    command: "python3 /home/sn0wb/action/FinalRecon/finalrecon.py -nb --crawl --headers --whois --dns --dir --full --url http://{target} | grep -vE 'Requesting|API key not found|Skipping|Scanning|Requests'"    

  - name: katana
    command: "katana -u {target} --headless -d 3 -aff"    

scan:
  - name: xsstrike
    command: "python3 /home/sn0wb/action/XSStrike/xsstrike.py -u {target} --crawl --blind --skip"    
  - name: sqlmap
    command: "sqlmap {target} -batch"  

    